// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(DIYTypelessCoreFFI)
import DIYTypelessCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_diy_typeless_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_diy_typeless_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDiyTypelessCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Cooperative cancellation token for long-running operations.
 */
public protocol CancellationTokenProtocol: AnyObject, Sendable {
    
    /**
     * Request cancellation.
     */
    func cancel() 
    
    /**
     * Check whether cancellation has been requested.
     */
    func isCancelled()  -> Bool
    
}
/**
 * Cooperative cancellation token for long-running operations.
 */
open class CancellationToken: CancellationTokenProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_diy_typeless_core_fn_clone_cancellationtoken(self.handle, $0) }
    }
    /**
     * Create a new token in non-cancelled state.
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_diy_typeless_core_fn_constructor_cancellationtoken_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_diy_typeless_core_fn_free_cancellationtoken(handle, $0) }
    }

    

    
    /**
     * Request cancellation.
     */
open func cancel()  {try! rustCall() {
    uniffi_diy_typeless_core_fn_method_cancellationtoken_cancel(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Check whether cancellation has been requested.
     */
open func isCancelled() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_diy_typeless_core_fn_method_cancellationtoken_is_cancelled(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCancellationToken: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CancellationToken

    public static func lift(_ handle: UInt64) throws -> CancellationToken {
        return CancellationToken(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CancellationToken) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CancellationToken {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CancellationToken, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCancellationToken_lift(_ handle: UInt64) throws -> CancellationToken {
    return try FfiConverterTypeCancellationToken.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCancellationToken_lower(_ value: CancellationToken) -> UInt64 {
    return FfiConverterTypeCancellationToken.lower(value)
}




/**
 * Captured audio payload and metadata.
 */
public struct AudioData: Equatable, Hashable {
    /**
     * Encoded audio bytes in FLAC format.
     */
    public var bytes: Data
    /**
     * Approximate capture duration in seconds before post-processing.
     */
    public var durationSeconds: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Encoded audio bytes in FLAC format.
         */bytes: Data, 
        /**
         * Approximate capture duration in seconds before post-processing.
         */durationSeconds: Float) {
        self.bytes = bytes
        self.durationSeconds = durationSeconds
    }

    

    
}

#if compiler(>=6)
extension AudioData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioData {
        return
            try AudioData(
                bytes: FfiConverterData.read(from: &buf), 
                durationSeconds: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: AudioData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
        FfiConverterFloat.write(value.durationSeconds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioData_lift(_ buf: RustBuffer) throws -> AudioData {
    return try FfiConverterTypeAudioData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioData_lower(_ value: AudioData) -> RustBuffer {
    return FfiConverterTypeAudioData.lower(value)
}


public struct PipelineResult: Equatable, Hashable {
    public var rawText: String
    public var polishedText: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rawText: String, polishedText: String) {
        self.rawText = rawText
        self.polishedText = polishedText
    }

    

    
}

#if compiler(>=6)
extension PipelineResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePipelineResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PipelineResult {
        return
            try PipelineResult(
                rawText: FfiConverterString.read(from: &buf), 
                polishedText: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PipelineResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rawText, into: &buf)
        FfiConverterString.write(value.polishedText, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePipelineResult_lift(_ buf: RustBuffer) throws -> PipelineResult {
    return try FfiConverterTypePipelineResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePipelineResult_lower(_ value: PipelineResult) -> RustBuffer {
    return FfiConverterTypePipelineResult.lower(value)
}


/**
 * Unified error type returned by core operations.
 */
public enum CoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Operation was cancelled by caller.
     */
    case Cancelled
    /**
     * No default input audio device is available.
     */
    case AudioDeviceUnavailable
    /**
     * Recording was started while another capture session is active.
     */
    case RecordingAlreadyActive
    /**
     * Recording was stopped without an active capture session.
     */
    case RecordingNotActive
    /**
     * Audio capture failed.
     */
    case AudioCapture(String
    )
    /**
     * Audio processing failed.
     */
    case AudioProcessing(String
    )
    /**
     * HTTP transport failed.
     */
    case Http(String
    )
    /**
     * Remote API returned a non-success response.
     */
    case Api(String
    )
    /**
     * Serialization or deserialization failed.
     */
    case Serialization(String
    )
    /**
     * API returned no usable content.
     */
    case EmptyResponse
    /**
     * Transcription operation failed.
     */
    case Transcription(String
    )
    /**
     * Configuration is invalid or missing.
     */
    case Config(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Cancelled
        case 2: return .AudioDeviceUnavailable
        case 3: return .RecordingAlreadyActive
        case 4: return .RecordingNotActive
        case 5: return .AudioCapture(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .AudioProcessing(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .Http(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .Api(
            try FfiConverterString.read(from: &buf)
            )
        case 9: return .Serialization(
            try FfiConverterString.read(from: &buf)
            )
        case 10: return .EmptyResponse
        case 11: return .Transcription(
            try FfiConverterString.read(from: &buf)
            )
        case 12: return .Config(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Cancelled:
            writeInt(&buf, Int32(1))
        
        
        case .AudioDeviceUnavailable:
            writeInt(&buf, Int32(2))
        
        
        case .RecordingAlreadyActive:
            writeInt(&buf, Int32(3))
        
        
        case .RecordingNotActive:
            writeInt(&buf, Int32(4))
        
        
        case let .AudioCapture(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .AudioProcessing(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Http(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Api(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Serialization(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .EmptyResponse:
            writeInt(&buf, Int32(10))
        
        
        case let .Transcription(v1):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Config(v1):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * Polish raw transcript text with Gemini API.
 */
public func polishText(apiKey: String, rawText: String, context: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_polish_text(
        FfiConverterString.lower(apiKey),
        FfiConverterString.lower(rawText),
        FfiConverterOptionString.lower(context),$0
    )
})
}
/**
 * Polish raw transcript text with Gemini API.
 *
 * Supports cooperative cancellation using a shared cancellation token.
 */
public func polishTextCancellable(apiKey: String, rawText: String, context: String?, cancellationToken: CancellationToken)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_polish_text_cancellable(
        FfiConverterString.lower(apiKey),
        FfiConverterString.lower(rawText),
        FfiConverterOptionString.lower(context),
        FfiConverterTypeCancellationToken_lower(cancellationToken),$0
    )
})
}
/**
 * Process text with LLM (Gemini API)
 * Generic function for processing text with custom prompts
 * Process arbitrary text with Gemini API and optional system instruction.
 */
public func processTextWithLlm(apiKey: String, prompt: String, systemInstruction: String?, temperature: Float?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_process_text_with_llm(
        FfiConverterString.lower(apiKey),
        FfiConverterString.lower(prompt),
        FfiConverterOptionString.lower(systemInstruction),
        FfiConverterOptionFloat.lower(temperature),$0
    )
})
}
/**
 * Start microphone capture.
 *
 * Returns an error if input audio device is unavailable or recording is already active.
 */
public func startRecording()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_start_recording($0
    )
}
}
/**
 * Stop microphone capture and return FLAC-encoded audio.
 *
 * The returned payload is optimized for transcription upload.
 */
public func stopRecording()throws  -> AudioData  {
    return try  FfiConverterTypeAudioData_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_stop_recording($0
    )
})
}
/**
 * Transcribe encoded audio bytes with Groq Whisper API.
 */
public func transcribeAudioBytes(apiKey: String, audioBytes: Data, language: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_transcribe_audio_bytes(
        FfiConverterString.lower(apiKey),
        FfiConverterData.lower(audioBytes),
        FfiConverterOptionString.lower(language),$0
    )
})
}
/**
 * Transcribe encoded audio bytes with Groq Whisper API.
 *
 * Supports cooperative cancellation using a shared cancellation token.
 */
public func transcribeAudioBytesCancellable(apiKey: String, audioBytes: Data, language: String?, cancellationToken: CancellationToken)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_transcribe_audio_bytes_cancellable(
        FfiConverterString.lower(apiKey),
        FfiConverterData.lower(audioBytes),
        FfiConverterOptionString.lower(language),
        FfiConverterTypeCancellationToken_lower(cancellationToken),$0
    )
})
}
/**
 * Warm up TLS connection to Gemini API
 *
 * Call this at the start of recording to eliminate TLS handshake latency.
 * See [`http_client::warmup_gemini_connection`] for detailed timing considerations.
 *
 * # Important
 * - The connection pool has a 300-second idle timeout
 * - For long recording sessions, consider re-warming before polish
 * - This should be called immediately before or at the start of recording
 * Warm up TLS connection to Gemini API.
 */
public func warmupGeminiConnection()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_warmup_gemini_connection($0
    )
}
}
/**
 * Warm up TLS connection to Groq API
 *
 * Call this at the start of recording to eliminate TLS handshake latency.
 * See [`http_client::warmup_groq_connection`] for detailed timing considerations.
 *
 * # Important
 * - The connection pool has a 300-second idle timeout
 * - For recordings longer than ~4 minutes, the connection may need re-warming
 * - This should be called immediately before or at the start of recording
 * Warm up TLS connection to Groq API.
 */
public func warmupGroqConnection()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_diy_typeless_core_fn_func_warmup_groq_connection($0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_diy_typeless_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_polish_text() != 45710) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_polish_text_cancellable() != 31763) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_process_text_with_llm() != 56597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_start_recording() != 20492) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_stop_recording() != 22176) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_transcribe_audio_bytes() != 3876) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_transcribe_audio_bytes_cancellable() != 47248) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_warmup_gemini_connection() != 13024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_func_warmup_groq_connection() != 35656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_method_cancellationtoken_cancel() != 9674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_method_cancellationtoken_is_cancelled() != 51790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_diy_typeless_core_checksum_constructor_cancellationtoken_new() != 61982) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDiyTypelessCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all